env:
  EXECUTABLES: "corewar"

name: corewar
run-name: corewar
on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v4.2.2

      - name: Run checker
        shell: bash
        run: |
          check.sh $(pwd) $(pwd)
          if [ -f coding-style-reports.log ]; then
            error_exit=0
            while IFS= read -r line ; do
            FILE=$(echo $line | awk -F ':' '{print $1}')
            LINE=$(echo $line | awk -F ':' '{print $2}')
            SEVERITY=$(echo $line | awk -F ':' '{print $3}')
            ERROR=$(echo $line | awk -F ':' '{print $4}')
            if [ "${SEVERITY}" != "INFO" ]; then
              echo "::error title=$SEVERITY,file=$FILE,line=$LINE::$ERROR"
              error_exit=1
            else
              echo "::warning title=$SEVERITY,file=$FILE,line=$LINE::$ERROR"
            fi
            done < coding-style-reports.log
            if [ "${error_exit}" == 1 ]; then
              exit 1
            fi
          fi

  check_program_compilation:
    runs-on: ubuntu-latest
    needs: check_coding_style
    container: epitechcontent/epitest-docker

    steps:
      - name: Checkout files
        uses: actions/checkout@v4.2.2

      - name: Download make
        run: sudo apt install make

      - name: Run make
        timeout-minutes: 2
        shell: bash
        run: |
          make

      - name: Run make clean
        run: |
          make clean

      - name: check executables
        shell: bash
        run: |
          exit_error=0
          for file in ${{ env.EXECUTABLES }}; do
          if [ -x "$file" ]; then
            echo "'$file' is executable"
          else
            exit_error=1
          fi
          done
          if [ "${error_exit}" == 1 ]; then
            exit 1
          fi
