env:
  EXECUTABLES: "corewar"

name: corewar
run-name: corewar
on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

jobs:
  check_program_compilation:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker

    steps:
      - name: Checkout files
        uses: actions/checkout@v4.2.2

      - name: Download make
        run: sudo apt install make

      - name: Download dependencies
        timeout-minutes: 5
        shell: bash
        run: |
          ./installer.sh

      - name: Run make
        timeout-minutes: 2
        shell: bash
        run: |
          make

      - name: Run make clean
        run: |
          make clean

      - name: check executables
        shell: bash
        run: |
          exit_error=0
          for file in ${{ env.EXECUTABLES }}; do
          if [ -x "$file" ]; then
            echo "'$file' is executable"
          else
            exit_error=1
          fi
          done
          if [ "${error_exit}" == 1 ]; then
            exit 1
          fi
